<?php
    return [ "users" =>
        [
            "name",
            "email",
            "email_verified_at",
            "phone",
            "phone_verified_at",
            "password",
            "city_id",
            "image",
            "is_active",
            "verification_code",
            "api_token",
            "type",
            "deleted_at",
            "fcm_token",
            "is_dark",
        ]
    ];
?>
